#!/bin/bash

# Exit if no argument is given
if [ $# -eq 0 ]; then
    echo "Bitte übergib den Programmnamen oder den Pfad zur Datei als Parameter"
    exit 1
fi
# --box umu
# --bind /mnt/bf47eb5b-1649-47ef-b481-8807b641d087/umu/ /
cmd="--stdir --debug --pass ./ --enable-userns --setenv PATH \"$PATH\" --gpu --setenv LD_LIBRARY_PATH /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/lib/i386-linux-gnu:/usr/lib/i386-linux-gnu:/lib32:/usr/lib32 --tmpfs $XDG_RUNTIME_DIR --ro-pass /etc/machine-id --video --audio --share-ipc --setenv WINEDEBUG \"-all\" --pass ~/.local/share/Steam --tui --setenv PROTONPATH '/home/user/.local/share/Steam/compatibilitytools.d/GE-Proton10-34/' --stenv WINEDEBUG '-all'" #--setenv WINEDEBUG \"err+all\" --setenv WINEARCH win64 --share-ipc
# --setenv PLATFORM /usr/lib/pressure-vessel/from-host/libexec/steam-runtime-tools-0/i386-linux-gnu-detect-platform

shortcut=false
chdir=""
home=""
if [ $# -gt 0 ]; then
    for ((i=1 ; i<=$# ; i++ )); do
        arg=${!i}
        case "$arg" in
            --video) {
                cmd="${cmd//--video/}"
                if [[ "$XDG_SESSION_TYPE" == "wayland" && -e "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" && "$WAYLAND_DISPLAY" != "" ]]; then
    #             if [[ "$XDG_SESSION_TYPE" == "wayland" && "$WAYLAND_DISPLAY" != "" ]]; then # can't be used because of xwayland
                    cmd="$cmd --setenv XDG_SESSION_TYPE \"$XDG_SESSION_TYPE\" --setenv WAYLAND_DISPLAY \"$WAYLAND_DISPLAY\" --ro-bind \"$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY\" \"$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY\""
    #             elif [[ "$XDG_SESSION_TYPE" == "x11" && "$DISPLAY" != "" ]]; then
                elif [[ "$XDG_SESSION_TYPE" == "x11" && -e "/tmp/.X11-unix/" && "$DISPLAY" != "" ]]; then
                    ((i++))
                    if [[ "${!i}" == *":"* ]]; then
                        cmd="$cmd --setenv DISPLAY \"${!i}\" --ro-bind /tmp/.X11-unix/X${!i/:/} /tmp/.X11-unix/X${!i/:/}"
                    else
                        ((i--))
                        cmd="$cmd --setenv DISPLAY \":0\" --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0"
                    fi
                fi
            };;
            --chdir) {
                ((i++))
                chdir=" start /d\"${!i}\""
            };;
            # --shortcut) {
            #     shortcut=true
            # };;
            --input) {
                cmd="$cmd --input"
            };;
            --noseccomp) {
                cmd="$cmd --noseccomp"
            };;
            --no-audio|--disable-audio) {
                cmd="${cmd//--audio/}"
            };;
#             --x11-sandbox|--disable-x11) {
#                 cmd="${cmd//--video/--x11-sandbox}"
#             };;
            --net) {
                cmd="$cmd --net"
            };;
            --xdg-runtime-dir) {
                cmd="${cmd//--tmpfs $XDG_RUNTIME_DIR/--ro-pass $XDG_RUNTIME_DIR}"
            };;
            --devices) {
                cmd="$cmd --dev-pass /dev"
            };;
            --usb) {
                cmd="${cmd} --usb"
            };;
            --ro-usb) {
                cmd="${cmd} --ro-usb"
            };;
            --log|--logging) {
                cmd="$cmd --setenv PROTONLOG 1"
            };;
            --no-fsync) {
                cmd="$cmd --setenv PROTON_NO_FSYNC 1"
            };;
            --sandbox) {
                sandbox=true
            };;
            --home) {
                ((i++))
                cmd="--bind ${!i} / $cmd"
                home="${!i}"
            };;
            --desktop-portal) {
                cmd="$cmd --desktop-portal"
            };;
            *) {
                if [ "$WINEPREFIX" == "" ]; then
                    if [[ "$arg" == *"$HOME/Games/"* ]]; then
                        WINEPREFIX="${arg//$HOME\/Games\//}"
                        IFS='/' read -r -a array <<< "$WINEPREFIX"
                        WINEPREFIX=${array[0]}
                    else
                        WINEPREFIX="$arg"
                    fi
                fi
                cmd="$cmd --setenv WINEPREFIX '$HOME/Games/$WINEPREFIX'"

                if [ "$PROTONPATH" != "" ]; then
                    cmd="$cmd --pass '$PROTONPATH' --setenv PROTONPATH '$PROTONPATH'"
                fi

                if [ "$PROTON_NO_ESYNC" != "" ]; then
                    cmd="$cmd --setenv PROTON_NO_ESYNC '$PROTON_NO_ESYNC'"
                fi

                if [ "$DXVK_ASYNC" != "" ]; then
                    cmd="$cmd --setenv DXVK_ASYNC '$DXVK_ASYNC'"
                fi

                if [ "$PROTON_LOG" != "" ]; then
                    cmd="$cmd --setenv PROTONLOG $PROTON_LOG"
                fi
                if [ "$PROTON_NO_FSYNC" != "" ]; then
                    cmd="$cmd --setenv PROTON_NO_FSYNC '$PROTON_NO_FSYNC'"
                fi
                if [ "$WINEDLLOVERWRITES" != "" ]; then
                    cmd="$cmd --setenv WINEDLLOVERRIDES '$WINEDLLOVERWRITES'"
                fi
                if [ "$WINEDLLOVERRIDES" != "" ]; then
                    cmd="$cmd --setenv WINEDLLOVERRIDES '$WINEDLLOVERRIDES'"
                fi
                cmd="bash bubblejail $cmd"
                cmd="$cmd -p umu/umu-run" #--setenv PROTON_LOG_DIR ~
                if [[ "$chdir" != "" ]]; then
                    cmd="$cmd $chdir"
                fi
                cmd="$cmd \"$arg\""
                ((i++))
                for ((l=$i; l<=$#; l++)); do
                    cmd="$cmd '${!l}'"
                done

                if [[ "$shortcut" == true && ! -e "$HOME/Schreibtisch/test.desktop" ]]; then
                    tmp="[Desktop Entry]
Name='${arg//\//\_}'
Comment=Run a game via UMU
Exec='${cmd}'
#Icon=steam
Terminal=true
Type=Game
Categories=Game;" 
                echo "$tmp" > $HOME/Schreibtisch/test.desktop
                chmod a+x $HOME/Schreibtisch/test.desktop
                fi
                break
            };;
        esac
    done
fi

if [[ $sandbox == true ]]; then
    if [[ "$home" != "" ]]; then
        echo "WINEPREFIX=\"$WINEPREFIX\" bash umu-sandbox --home '$home' --ro-usb winetricks settings sandbox"
        eval "WINEPREFIX=\"$WINEPREFIX\" bash umu-sandbox --home '$home' --ro-usb winetricks settings sandbox"
    else
        echo "WINEPREFIX=\"$WINEPREFIX\" bash umu-sandbox --ro-usb winetricks settings sandbox"
        eval "WINEPREFIX=\"$WINEPREFIX\" bash umu-sandbox --ro-usb winetricks settings sandbox"
    fi
fi


echo "$cmd"

eval "$cmd"
